version: "2"
services:
  ultimate-webbackend:
    build:
      context: ../../
      dockerfile: "Dockerfile"
      target: "ultimate-webbackend"
    image: "ultimate-webbackend"
    env_file:
      - "ultimate-webbackend.env"
    ports:
      - "8080:8080"
    restart: "unless-stopped"

  ultimate-websitestatic:
    build:
      context: ../../
      dockerfile: "Dockerfile"
      target: "ultimate-websitestatic"
    image: "ultimate-websitestatic"
    env_file:
      - "ultimate-websitestatic.env"
    ports:
      - "80:80"
    restart: "unless-stopped"
